# Schema for the configuration files of the Weather module.
weather.settings:
  type: config_object
  label: 'Weather settings'
  mapping:
    url:
      type: string
      label: 'API URL'
    api_key:
      type: string
      label: 'API Key'
    units:
      type: string
      label: 'Unit'
    cnt:
      type: integer
      label: 'Number of timestamps to retrieve'

